export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

export const USER_LOGOUT = "USER_LOGOUT"

export const USER_PROFILE_UPDATE_PENDING = "USER_PROFILE_UPDATE_PENDING"
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS"
export const USER_PROFILE_UPDATE_ERROR = "USER_PROFILE_UPDATE_ERROR"

export const USER_POSITIONING_DISABLE = "USER_POSITIONING_DISABLE"
export const USER_LOCATION_UPDATE = "USER_LOCATION_UPDATE"

export const USER_POSITIONING_PENDING = "USER_POSITIONING_PENDING"
export const USER_POSITIONING_SUCCESS = "USER_POSITIONING_SUCCESS"
export const USER_POSITIONING_ERROR = "USER_POSITIONING_ERROR"


export const SELECT_REPORT = "SELECT_REPORT"
export const DESELECT_REPORT = "DESELECT_REPORT"

export const REPORT_SUBMIT_PENDING = "REPORT_SUBMIT_PENDING"
export const REPORT_SUBMIT_SUCCESS = "REPORT_SUBMIT_SUCCESS"
export const REPORT_SUBMIT_ERROR = "REPORT_SUBMIT_ERROR"

export const FETCH_OLD_REPORTS = "FETCH_OLD_REPORTS"
export const RECEIVE_NEW_REPORTS = "RECEIVE_NEW_REPORTS"

export const SYNCHRONIZE_TIMER = "SYNCHRONIZE_TIMER"

export const TOGGLE_TIMER_PENDING = "TOGGLE_TIMER_PENDING"
export const TOGGLE_TIMER_SUCCESS = "TOGGLE_TIMER_SUCCESS"
export const TOGGLE_TIMER_ERROR = "TOGGLE_TIMER_ERROR"

export const SYNCHRONIZE_ALLOWANCE = "SYNCHRONIZE_ALLOWANCE"

export const FETCH_SUMMARY_PENDING = "FETCH_SUMMARY_PENDING"
export const FETCH_SUMMARY_SUCCESS = "FETCH_SUMMARY_SUCCESS"
export const FETCH_SUMMARY_ERROR = "FETCH_SUMMARY_ERROR"
