export const USER_LOGIN = 'USER_LOGIN'
export const USER_REGISTER = "USER_REGISTER"
export const USER_LOGOUT = "USER_LOGOUT"
export const USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE"

export const REPORT_SUBMIT = "REPORT_SUBMIT"
export const FETCH_OLD_REPORTS = "FETCH_OLD_REPORTS"
export const RECEIVE_NEW_REPORTS = "RECEIVE_NEW_REPORTS"

export const SYNCHRONIZE_TIMER = "SYNCHRONIZE_TIMER"
export const TOGGLE_TIMER = "TOGGLE_TIMER"
export const SYNCHRONIZE_ALLOWANCE = "SYNCHRONIZE_ALLOWANCE";
