export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

export const USER_LOGOUT = "USER_LOGOUT"

export const USER_PROFILE_UPDATE_PENDING = "USER_PROFILE_UPDATE_PENDING"
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS"
export const USER_PROFILE_UPDATE_ERROR = "USER_PROFILE_UPDATE_ERROR"

export const USER_POSITIONING_DISABLE = "USER_POSITIONING_DISABLE"
export const USER_LOCATION_UPDATE = "USER_LOCATION_UPDATE"


export const REPORT_SUBMIT = "REPORT_SUBMIT"
export const FETCH_OLD_REPORTS = "FETCH_OLD_REPORTS"
export const RECEIVE_NEW_REPORTS = "RECEIVE_NEW_REPORTS"

export const SYNCHRONIZE_TIMER = "SYNCHRONIZE_TIMER"
export const TOGGLE_TIMER = "TOGGLE_TIMER"
export const SYNCHRONIZE_ALLOWANCE = "SYNCHRONIZE_ALLOWANCE";
